name: run all_schedule.py

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 20 * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v3

      - name: install python packages
        run: pip install -r requirements.txt

      - name: execute py script # run all_schedule.py
        run: python all_schedule.py